apiVersion: v1
name: sns-chart
description: A Helm chart for the ACK service controller for Amazon Simple Notification Service (SNS)
version: 1.0.5
appVersion: 1.0.5
home: https://github.com/aws-controllers-k8s/sns-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/sns-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: SNS Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/sns-maintainer
keywords:
  - aws
  - kubernetes
  - sns
