image:
  repository: questdb/questdb
  pullPolicy: IfNotPresent
  tag: 6.1.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

questdb:
  config:
    enabled: true
    options:
      http.enabled: false # Do not expose the Web Console

config:
  service_worker_count: 2
  db_root: db
  db_backup_root: backups
  pg_user: admin
  pg_password: quest
  enable_telemetry: true

service:
  annotations: {}
  type: ClusterIP
  port: 9000
  expose:
    postgresql:
      enabled: true
      port: 8812
    influxdb:
      enabled: true
      port: 9009
    healthcheck:
      enabled: true
      port: 9003

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi

ingress:
  enabled: false
  hosts: []
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
