apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nginx-ingress.controller.fullname" . }}
data:
  enable-vts-status: "{{ .Values.controller.stats.enabled }}"
{{- if .Values.controller.wallarm.enabled }}
  enable-wallarm: "{{ .Values.controller.wallarm.enabled }}"
  enable-wallarm-acl: "{{ .Values.controller.wallarm.acl.enabled }}"
  wallarm-upstream-service: "{{ .Release.Namespace }}/{{ template "nginx-ingress.controller.fullname" . }}-wallarm-tarantool"
{{- end }}
{{- if .Values.controller.headers }}
  proxy-set-headers: {{ .Release.Namespace }}/{{ template "nginx-ingress.fullname" . }}-custom-headers
{{- end }}
{{- if .Values.controller.wallarm.fallback }}
  wallarm-fallback: "{{ .Values.controller.wallarm.fallback }}"
{{- end }}

{{- if .Values.controller.config }}
{{ toYaml .Values.controller.config | indent 2 }}
{{- end }}
