apiVersion: v2
name: nri-kube-events
description: A Helm chart to deploy the New Relic Kube Events router
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
sources:
  - https://github.com/newrelic/nri-kube-events/
  - https://github.com/newrelic/nri-kube-events/tree/main/charts/nri-kube-events
  - https://github.com/newrelic/infrastructure-agent/
version: 3.9.4
appVersion: 2.9.4
dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"
maintainers:
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
keywords:
  - infrastructure
  - newrelic
  - monitoring
