apiVersion: v1
name: prometheusservice-chart
description: A Helm chart for the ACK service controller for Amazon Managed Service for Prometheus (AMP)
version: 1.2.5
appVersion: 1.2.5
home: https://github.com/aws-controllers-k8s/prometheusservice-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/prometheusservice-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: AMP Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/prometheusservice-maintainer
keywords:
  - aws
  - kubernetes
  - prometheusservice
