apiVersion: v2
appVersion: 1.22.0
dependencies:
- alias: datadogCRDs
  condition: installCRDs
  name: datadog-crds
  repository: https://helm.datadoghq.com
  tags:
  - install-crds
  version: 2.15.0
description: Datadog Operator
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
keywords:
- monitoring
- alerting
- metric
maintainers:
- email: support@datadoghq.com
  name: Datadog
name: datadog-operator
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
version: 2.17.0
