apiVersion: v1
name: eventbridge-chart
description: A Helm chart for the ACK service controller for Amazon EventBridge (EventBridge)
version: 1.0.4
appVersion: 1.0.4
home: https://github.com/aws-controllers-k8s/eventbridge-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/eventbridge-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: EventBridge Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/eventbridge-maintainer
keywords:
  - aws
  - kubernetes
  - eventbridge
