apiVersion: v2
name: newrelic-prometheus-agent
description: A Helm chart to deploy Prometheus with New Relic Prometheus Configurator.
type: application
version: 1.12.0
# Prometheus Server Version
# https://pkg.go.dev/github.com/prometheus/prometheus#readme-prometheus-code-base
appVersion: "v2.37.8"
annotations:
  configuratorVersion: "1.15.0"
dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"
keywords:
  - newrelic
  - prometheus
maintainers:
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
